-- =====================================================================
-- KYC schema for PostgreSQL
-- Run with: psql -U <user> -d <database> -f kyc_postgres.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Nepal geography, normalized into provinces / districts /
--    municipalities, seeded from script/geography.csv (7 provinces,
--    77 districts, 753 local levels).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provinces (
    id   INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS districts (
    id          INTEGER PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    province_id INTEGER NOT NULL REFERENCES provinces(id),
    CONSTRAINT uq_districts_province_id_name UNIQUE (province_id, name)
);

CREATE TABLE IF NOT EXISTS municipalities (
    id          INTEGER PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    district_id INTEGER NOT NULL REFERENCES districts(id),
    CONSTRAINT uq_municipalities_district_id_name UNIQUE (district_id, name)
);

CREATE INDEX IF NOT EXISTS idx_districts_province_id ON districts (province_id);
CREATE INDEX IF NOT EXISTS idx_municipalities_district_id ON municipalities (district_id);

-- ---------------------------------------------------------------------
-- 2. Bulk insert of provinces, districts and municipalities.
--    ON CONFLICT DO NOTHING makes this safe to re-run.
-- ---------------------------------------------------------------------
INSERT INTO provinces (id, name) VALUES
    (1, 'Koshi Province'),
    (2, 'Madhesh Province'),
    (3, 'Bagmati'),
    (4, 'Gandaki'),
    (5, 'Lumbini'),
    (6, 'Karnali'),
    (7, 'Sudur Paschimanchal')
ON CONFLICT (id) DO NOTHING;

INSERT INTO districts (id, name, province_id) VALUES
    (1, 'Bhojpur', 1),
    (2, 'Dhankuta', 1),
    (3, 'Ilam', 1),
    (4, 'Jhapa', 1),
    (5, 'Khotang', 1),
    (6, 'Morang', 1),
    (7, 'Okhaldhunga', 1),
    (8, 'Pachthar', 1),
    (9, 'Sankhuwasabha', 1),
    (10, 'Solukhumbu', 1),
    (11, 'Sunsari', 1),
    (12, 'Taplejung', 1),
    (13, 'Terhathum', 1),
    (14, 'Udayapur', 1),
    (15, 'Parsa', 2),
    (16, 'Bara', 2),
    (17, 'Rautahat', 2),
    (18, 'Sarlahi', 2),
    (19, 'Siraha', 2),
    (20, 'Dhanusha', 2),
    (21, 'Saptari', 2),
    (22, 'Mahottari', 2),
    (23, 'Bhaktapur', 3),
    (24, 'Chitwan', 3),
    (25, 'Dhading', 3),
    (26, 'Dolakha', 3),
    (27, 'Kathmandu', 3),
    (28, 'Kavrepalanchok', 3),
    (29, 'Lalitpur', 3),
    (30, 'Makwanpur', 3),
    (31, 'Nuwakot', 3),
    (32, 'Ramechap', 3),
    (33, 'Rasuwa', 3),
    (34, 'Sindhuli', 3),
    (35, 'Sindhupalchok', 3),
    (36, 'Baglung', 4),
    (37, 'Gorkha', 4),
    (38, 'Kaski', 4),
    (39, 'Lamjung', 4),
    (40, 'Manang', 4),
    (41, 'Mustang', 4),
    (42, 'Myagdi', 4),
    (43, 'Nawalpur', 4),
    (44, 'Parwat', 4),
    (45, 'Syangja', 4),
    (46, 'Tanahun', 4),
    (47, 'Kapilvastu', 5),
    (48, 'Parasi', 5),
    (49, 'Rupandehi', 5),
    (50, 'Arghakhanchi', 5),
    (51, 'Gulmi', 5),
    (52, 'Palpa', 5),
    (53, 'Dang', 5),
    (54, 'Pyuthan', 5),
    (55, 'Rolpa', 5),
    (56, 'Eastern Rukum', 5),
    (57, 'Banke', 5),
    (58, 'Bardiya', 5),
    (59, 'Western Rukum', 6),
    (60, 'Salyan', 6),
    (61, 'Dolpa', 6),
    (62, 'Humla', 6),
    (63, 'Jumla', 6),
    (64, 'Kalikot', 6),
    (65, 'Mugu', 6),
    (66, 'Surkhet', 6),
    (67, 'Dailekh', 6),
    (68, 'Jajarkot', 6),
    (69, 'Darchula', 7),
    (70, 'Bajhang', 7),
    (71, 'Bajura', 7),
    (72, 'Baitadi', 7),
    (73, 'Doti', 7),
    (74, 'Acham', 7),
    (75, 'Dadeldhura', 7),
    (76, 'Kanchanpur', 7),
    (77, 'Kailali', 7)
ON CONFLICT (id) DO NOTHING;

INSERT INTO municipalities (id, name, district_id) VALUES
    (1, 'Shadanand Municipality', 1),
    (2, 'Bhojpur Municipality', 1),
    (3, 'Hatuwagadhi Rural Municipality', 1),
    (4, 'Ramprasad Rai Rural Municipality', 1),
    (5, 'Aamchok Rural Municipality', 1),
    (6, 'Tyamke Maiyum Rural Municipality', 1),
    (7, 'Arun Rural Municipality', 1),
    (8, 'Pauwadungma Rural Municipality', 1),
    (9, 'Salpasilichho Rural Municipality', 1),
    (10, 'Dhankuta Municipality', 2),
    (11, 'Pakhribas Municipality', 2),
    (12, 'Mahalaxmi Municipality', 2),
    (13, 'Sangurigadhi Rural Municipality', 2),
    (14, 'Chaubise Rural Municipality', 2),
    (15, 'Sahidbhumi Rural Municipality', 2),
    (16, 'Chhathar Jorpati Rural Municipality', 2),
    (17, 'Suryodaya Municipality', 3),
    (18, 'Ilam Municipality', 3),
    (19, 'Deumai Municipality', 3),
    (20, 'Maijogmai Rural Municipality', 3),
    (21, 'Phakphokthum Rural Municipality', 3),
    (22, 'Mai Municipality', 3),
    (23, 'Chulachuli Rural Municipality', 3),
    (24, 'Rong Rural Municipality', 3),
    (25, 'Mangsebung Rural Municipality', 3),
    (26, 'Sandakpur Rural Municipality', 3),
    (27, 'Mechinagar Municipality', 4),
    (28, 'Birtamod Municipality', 4),
    (29, 'Damak Municipality', 4),
    (30, 'Bhadrapur Municipality', 4),
    (31, 'Shivasatakshi Municipality', 4),
    (32, 'Arjundhara Municipality', 4),
    (33, 'Gauradaha Municipality', 4),
    (34, 'Kankai Municipality', 4),
    (35, 'Kamal Rural Municipality', 4),
    (36, 'Buddha Shanti Rural Municipality', 4),
    (37, 'Kachankawal Rural Municipality', 4),
    (38, 'Jhapa Rural Municipality', 4),
    (39, 'Barhadashi Rural Municipality', 4),
    (40, 'Gaurigunj Rural Municipality', 4),
    (41, 'Haldibari Rural Municipality', 4),
    (42, 'Diktel Rupakot Majhuwagadhi Municipality', 5),
    (43, 'Halesi Tuwachung Municipality', 5),
    (44, 'Khotehang Rural Municipality', 5),
    (45, 'Diprung Chuichumma Rural Municipality', 5),
    (46, 'Aiselukharka Rural Municipality', 5),
    (47, 'Jantedhunga Rural Municipality', 5),
    (48, 'Kepilasgadhi Rural Municipality', 5),
    (49, 'Barahpokhari Rural Municipality', 5),
    (50, 'Rawa Besi Rural Municipality', 5),
    (51, 'Sakela Rural Municipality', 5),
    (52, 'Sundar Haraicha Municipality', 6),
    (53, 'Belbari Municipality', 6),
    (54, 'Pathari Shanischare Municipality', 6),
    (55, 'Ratuwamai Municipality', 6),
    (56, 'Urlabari Municipality', 6),
    (57, 'Rangeli Municipality', 6),
    (58, 'Sunawarshi Municipality', 6),
    (59, 'Letang Municipality', 6),
    (60, 'Biratnagar Metropolitan City', 6),
    (61, 'Jahada Rural Municipality', 6),
    (62, 'Budi Ganga Rural Municipality', 6),
    (63, 'Katahari Rural Municipality', 6),
    (64, 'Dhanpalthan Rural Municipality', 6),
    (65, 'Kanepokhari Rural Municipality', 6),
    (66, 'Gramthan Rural Municipality', 6),
    (67, 'Kerabari Rural Municipality', 6),
    (68, 'Miklajung Rural Municipality', 6),
    (69, 'Siddhicharan Municipality', 7),
    (70, 'Khiji Demba Rural Municipality', 7),
    (71, 'Chisankhugadhi Rural Municipality', 7),
    (72, 'Molung Rural Municipality', 7),
    (73, 'Sunkoshi Rural Municipality', 7),
    (74, 'Champadevi Rural Municipality', 7),
    (75, 'Manebhanjyang Rural Municipality', 7),
    (76, 'Likhu Rural Municipality', 7),
    (77, 'Phidim Municipality', 8),
    (78, 'Miklajung Rural Municipality', 8),
    (79, 'Phalgunanda Rural Municipality', 8),
    (80, 'Hilihang Rural Municipality', 8),
    (81, 'Phalelung Rural Municipality', 8),
    (82, 'Yangwarak Rural Municipality', 8),
    (83, 'Kummayak Rural Municipality', 8),
    (84, 'Tumbewa Rural Municipality', 8),
    (85, 'Khandbari Municipality', 9),
    (86, 'Chainpur Municipality', 9),
    (87, 'Dharmadevi Municipality', 9),
    (88, 'Panchkhapan Municipality', 9),
    (89, 'Madi Municipality', 9),
    (90, 'Makalu Rural Municipality', 9),
    (91, 'Silichong Rural Municipality', 9),
    (92, 'Sabhapokhari Rural Municipality', 9),
    (93, 'Chichila Rural Municipality', 9),
    (94, 'BhotKhola Rural Municipality', 9),
    (95, 'Solu Dudhkunda Municipality', 10),
    (96, 'Mapya Dudhkoshi Rural Municipality', 10),
    (97, 'Necha Salyan Rural Municipality', 10),
    (98, 'Thulung Dudhkoshi Rural Municipality', 10),
    (99, 'Maha Kulung Rural Municipality', 10),
    (100, 'Sotang Rural Municipality', 10),
    (101, 'Khumbu PasangLhamu Rural Municipality', 10),
    (102, 'Likhu Pike Rural Municipality', 10),
    (103, 'BarahaKshetra Municipality', 11),
    (104, 'Inaruwa Municipality', 11),
    (105, 'Duhabi Municipality', 11),
    (106, 'Ramdhuni Municipality', 11),
    (107, 'Itahari Sub-Metropolitan City', 11),
    (108, 'Dharan Sub-Metropolitan City', 11),
    (109, 'Koshi Rural Municipality', 11),
    (110, 'Harinagar Rural Municipality', 11),
    (111, 'Bhokraha Narsingh Rural Municipality', 11),
    (112, 'Dewangunj Rural Municipality', 11),
    (113, 'Gadhi Rural Municipality', 11),
    (114, 'Barju Rural Municipality', 11),
    (115, 'Phungling Municipality', 12),
    (116, 'Sirijangha Rural Municipality', 12),
    (117, 'Aathrai Triveni Rural Municipality', 12),
    (118, 'Pathibhara Yangwarak Rural Municipality', 12),
    (119, 'Meringden Rural Municipality', 12),
    (120, 'Sidingwa Rural Municipality', 12),
    (121, 'Phaktanglung Rural Municipality', 12),
    (122, 'Maiwa Khola Rural Municipality', 12),
    (123, 'Mikwa Khola Rural Municipality', 12),
    (124, 'Myanglung Municipality', 13),
    (125, 'Laligurans Municipality', 13),
    (126, 'Aathrai Rural Municipality', 13),
    (127, 'Phedap Rural Municipality', 13),
    (128, 'Chhathar Rural Municipality', 13),
    (129, 'Menchayayem Rural Municipality', 13),
    (130, 'Triyuga Municipality', 14),
    (131, 'Katari Municipality', 14),
    (132, 'Chaudandigadhi Municipality', 14),
    (133, 'Belaka Municipality', 14),
    (134, 'Udayapurgadhi Rural Municipality', 14),
    (135, 'Rautamai Rural Municipality', 14),
    (136, 'Tapli Rural Municipality', 14),
    (137, 'Limchungbung Rural Municipality', 14),
    (138, 'Birgunj Metropolitan City', 15),
    (139, 'Bahudarmai Municipality', 15),
    (140, 'Parsagadhi Municipality', 15),
    (141, 'Pokhariya Municipality', 15),
    (142, 'Bindabasini Rural Municipality', 15),
    (143, 'Dhobini Rural Municipality', 15),
    (144, 'Chhipaharmai Rural Municipality', 15),
    (145, 'Jagarnathpur Rural Municipality', 15),
    (146, 'Jirabhawani Rural Municipality', 15),
    (147, 'Kalikamai Rural Municipality', 15),
    (148, 'Pakaha Mainpur Rural Municipality', 15),
    (149, 'Paterwa Sugauli Rural Municipality', 15),
    (150, 'Sakhuwa Prasauni Rural Municipality', 15),
    (151, 'Thori Rural Municipality', 15),
    (152, 'Kalaiya Sub-Metropolitan City', 16),
    (153, 'Jitpur Simara Sub-Metropolitan City', 16),
    (154, 'Kolhabi Municipality', 16),
    (155, 'Nijgadh Municipality', 16),
    (156, 'Mahagadhimai Municipality', 16),
    (157, 'Simaraungadh Municipality', 16),
    (158, 'Pacharauta Municipality', 16),
    (159, 'Pheta Rural Municipality', 16),
    (160, 'Bishrampur Rural Municipality', 16),
    (161, 'Prasauni Rural Municipality', 16),
    (162, 'Adarsh Kotwal Rural Municipality', 16),
    (163, 'Karaiyamai Rural Municipality', 16),
    (164, 'Devtal Rural Municipality', 16),
    (165, 'Parwanipur Rural Municipality', 16),
    (166, 'Baragadhi Rural Municipality', 16),
    (167, 'Suwarna Rural Municipality', 16),
    (168, 'Baudhimai Municipality', 17),
    (169, 'Brindaban Municipality', 17),
    (170, 'Chandrapur Municipality', 17),
    (171, 'Dewahi Gonahi Municipality', 17),
    (172, 'Gadhimai Municipality', 17),
    (173, 'Guruda Municipality', 17),
    (174, 'Gaur Municipality', 17),
    (175, 'Gujara Municipality', 17),
    (176, 'Ishanath Municipality', 17),
    (177, 'Katahariya Municipality', 17),
    (178, 'Madhav Narayan Municipality', 17),
    (179, 'Maulapur Municipality', 17),
    (180, 'Paroha Municipality', 17),
    (181, 'Phatuwa Bijayapur Municipality', 17),
    (182, 'Rajdevi Municipality', 17),
    (183, 'Rajpur Municipality', 17),
    (184, 'Durga Bhagwati Rural Municipality', 17),
    (185, 'Yamunamai Rural Municipality', 17),
    (186, 'Bagmati Municipality', 18),
    (187, 'Balara Municipality', 18),
    (188, 'Barahathwa Municipality', 18),
    (189, 'Godaita Municipality', 18),
    (190, 'Hariwan Municipality', 18),
    (191, 'Haripur Municipality', 18),
    (192, 'Haripurwa Municipality', 18),
    (193, 'Ishowrpur Municipality', 18),
    (194, 'Kabilasi Municipality', 18),
    (195, 'Lalbandi Municipality', 18),
    (196, 'Malangawa Municipality', 18),
    (197, 'Basbariya Rural Municipality', 18),
    (198, 'Bisnu Rural Municipality', 18),
    (199, 'Brahampuri Rural Municipality', 18),
    (200, 'Chakraghatta Rural Municipality', 18),
    (201, 'Chandranagar Rural Municipality', 18),
    (202, 'Dhankaul Rural Municipality', 18),
    (203, 'Kaudena Rural Municipality', 18),
    (204, 'Parsa Rural Municipality', 18),
    (205, 'Ramnagar Rural Municipality', 18),
    (206, 'Lahan Municipality', 19),
    (207, 'Dhangadhimai Municipality', 19),
    (208, 'Siraha Municipality', 19),
    (209, 'Golbazar Municipality', 19),
    (210, 'Mirchaiya Municipality', 19),
    (211, 'Kalyanpur Municipality', 19),
    (212, 'Karjanha Municipality', 19),
    (213, 'Sukhipur Municipality', 19),
    (214, 'Bhagwanpur Rural Municipality', 19),
    (215, 'Aurahi Rural Municipality', 19),
    (216, 'Bishnupur Rural Municipality', 19),
    (217, 'Bariyarpatti Rural Municipality', 19),
    (218, 'Lakshmipur Patari Rural Municipality', 19),
    (219, 'Naraha Rural Municipality', 19),
    (220, 'SakhuwanankarKatti Rural Municipality', 19),
    (221, 'Arnama Rural Municipality', 19),
    (222, 'Navarajpur Rural Municipality', 19),
    (223, 'Janakpurdham Sub-Metropolitan City', 20),
    (224, 'Chhireshwarnath Municipality', 20),
    (225, 'Ganeshman Charnath Municipality', 20),
    (226, 'Dhanushadham Municipality', 20),
    (227, 'Nagarain Municipality', 20),
    (228, 'Bideha Municipality', 20),
    (229, 'Mithila Municipality', 20),
    (230, 'Sahidnagar Municipality', 20),
    (231, 'Sabaila Municipality', 20),
    (232, 'Kamala Municipality', 20),
    (233, 'MithilaBihari Municipality', 20),
    (234, 'Hansapur Municipality', 20),
    (235, 'Janaknandani Rural Municipality', 20),
    (236, 'Bateshwar Rural Municipality', 20),
    (237, 'Mukhiyapatti Musharniya Rural Municipality', 20),
    (238, 'Lakshminya Rural Municipality', 20),
    (239, 'Aaurahi Rural Municipality', 20),
    (240, 'Dhanauji Rural Municipality', 20),
    (241, 'Bodebarsain Municipality', 21),
    (242, 'Dakneshwori Municipality', 21),
    (243, 'Hanumannagar Kankalini Municipality', 21),
    (244, 'Kanchanrup Municipality', 21),
    (245, 'Khadak Municipality', 21),
    (246, 'Shambhunath Municipality', 21),
    (247, 'Saptakoshi Municipality', 21),
    (248, 'Surunga Municipality', 21),
    (249, 'Rajbiraj Municipality', 21),
    (250, 'Agnisaira Krishnasavaran Rural Municipality', 21),
    (251, 'Balan-Bihul Rural Municipality', 21),
    (252, 'Rajgadh Rural Municipality', 21),
    (253, 'Bishnupur Rural Municipality', 21),
    (254, 'Chhinnamasta Rural Municipality', 21),
    (255, 'Mahadeva Rural Municipality', 21),
    (256, 'Rupani Rural Municipality', 21),
    (257, 'Tilathi Koiladi Rural Municipality', 21),
    (258, 'Tirhut Rural Municipality', 21),
    (259, 'Aaurahi Municipality', 22),
    (260, 'Balawa Municipality', 22),
    (261, 'Bardibas Municipality', 22),
    (262, 'Bhangaha Municipality', 22),
    (263, 'Gaushala Municipality', 22),
    (264, 'Jaleshor Municipality', 22),
    (265, 'Loharpatti Municipality', 22),
    (266, 'Manara Shiswa Municipality', 22),
    (267, 'Matihani Municipality', 22),
    (268, 'Ramgopalpur Municipality', 22),
    (269, 'Ekdara Rural Municipality', 22),
    (270, 'Mahottari Rural Municipality', 22),
    (271, 'Pipara Rural Municipality', 22),
    (272, 'Samsi Rural Municipality', 22),
    (273, 'Sonama Rural Municipality', 22),
    (274, 'Bhaktapur Municipality', 23),
    (275, 'Changunarayan Municipality', 23),
    (276, 'Suryabinayak Municipality', 23),
    (277, 'Madhyapur Thimi Municipality', 23),
    (278, 'Bharatpur Metropolitan City', 24),
    (279, 'Kalika Municipality', 24),
    (280, 'Khairhani Municipality', 24),
    (281, 'Madi Municipality', 24),
    (282, 'Ratnagar Municipality', 24),
    (283, 'Rapti Municipality', 24),
    (284, 'Ichchhakamana Rural Municipality', 24),
    (285, 'Dhunibeshi Municipality', 25),
    (286, 'Nilkantha Municipality', 25),
    (287, 'Khaniyabas Rural Municipality', 25),
    (288, 'Gajuri Rural Municipality', 25),
    (289, 'Galchhi Rural Municipality', 25),
    (290, 'Gangajamuna Rural Municipality', 25),
    (291, 'Jwalamukhi Rural Municipality', 25),
    (292, 'Thakre Rural Municipality', 25),
    (293, 'Netrawati Dabjong Rural Municipality', 25),
    (294, 'Benighat Rorang Rural Municipality', 25),
    (295, 'Rubi Valley Rural Municipality', 25),
    (296, 'Siddhalek Rural Municipality', 25),
    (297, 'Tripurasundari Rural Municipality', 25),
    (298, 'Bhimeswor Municipality', 26),
    (299, 'Jiri Municipality', 26),
    (300, 'Kalinchok Rural Municipality', 26),
    (301, 'Melung Rural Municipality', 26),
    (302, 'Bigu Rural Municipality', 26),
    (303, 'Gaurishankar Rural Municipality', 26),
    (304, 'Baiteshowr Rural Municipality', 26),
    (305, 'Sailung Rural Municipality', 26),
    (306, 'Tamakoshi Rural Municipality', 26),
    (307, 'Kathmandu Metropolitan City', 27),
    (308, 'Gokarneshwar Municipality', 27),
    (309, 'Kirtipur Municipality', 27),
    (310, 'Kageshwari-Manohara Municipality', 27),
    (311, 'Chandragiri Municipality', 27),
    (312, 'Tokha Municipality', 27),
    (313, 'Tarakeshwar Municipality', 27),
    (314, 'Dakshinkali Municipality', 27),
    (315, 'Nagarjun Municipality', 27),
    (316, 'Budhalikantha Municipality', 27),
    (317, 'Shankharapur Municipality', 27),
    (318, 'Dhulikhel Municipality', 28),
    (319, 'Namobuddha Municipality', 28),
    (320, 'Panauti Municipality', 28),
    (321, 'Panchkhal Municipality', 28),
    (322, 'Banepa Municipality', 28),
    (323, 'Mandandeupur Municipality', 28),
    (324, 'Khani Khola Rural Municipality', 28),
    (325, 'Chauri Deurali Rural Municipality', 28),
    (326, 'Temal Rural Municipality', 28),
    (327, 'Bethanchok Rural Municipality', 28),
    (328, 'Bhumlu Rural Municipality', 28),
    (329, 'Mahabharat Rural Municipality', 28),
    (330, 'Roshi Rural Municipality', 28),
    (331, 'Lalitpur Metropolitan City', 29),
    (332, 'Mahalaxmi Municipality', 29),
    (333, 'Godawari Municipality', 29),
    (334, 'Konjyosom Rural Municipality', 29),
    (335, 'Bagmati Rural Municipality', 29),
    (336, 'Mahankal Rural Municipality', 29),
    (337, 'Hetauda Sub-Metropolitan City', 30),
    (338, 'Thaha Municipality', 30),
    (339, 'Bhimphedi Rural Municipality', 30),
    (340, 'Makawanpurgadhi Rural Municipality', 30),
    (341, 'Manahari Rural Municipality', 30),
    (342, 'Raksirang Rural Municipality', 30),
    (343, 'Bakaiya Rural Municipality', 30),
    (344, 'Bagmati Rural Municipality', 30),
    (345, 'Kailash Rural Municipality', 30),
    (346, 'Indrasarowar Rural Municipality', 30),
    (347, 'Bidur Municipality', 31),
    (348, 'Belkotgadhi Municipality', 31),
    (349, 'Kakani Rural Municipality', 31),
    (350, 'Panchakanya Rural Municipality', 31),
    (351, 'Likhu Rural Municipality', 31),
    (352, 'Dupcheshwar Rural Municipality', 31),
    (353, 'Shivapuri Rural Municipality', 31),
    (354, 'Tadi Rural Municipality', 31),
    (355, 'Suryagadhi Rural Municipality', 31),
    (356, 'Tarkeshwar Rural Municipality', 31),
    (357, 'Kispang Rural Municipality', 31),
    (358, 'Myagang Rural Municipality', 31),
    (359, 'Manthali Municipality', 32),
    (360, 'Ramechhap Municipality', 32),
    (361, 'Umakunda Rural Municipality', 32),
    (362, 'Khandadevi Rural Municipality', 32),
    (363, 'Doramba Rural Municipality', 32),
    (364, 'Gokulganga Rural Municipality', 32),
    (365, 'LikhuTamakoshi Rural Municipality', 32),
    (366, 'Sunapati Rural Municipality', 32),
    (367, 'Kalika Rural Municipality', 33),
    (368, 'Gosaikunda Rural Municipality', 33),
    (369, 'Naukunda Rural Municipality', 33),
    (370, 'Parbatikunda Rural Municipality', 33),
    (371, 'Uttargaya Rural Municipality', 33),
    (372, 'Kamalamai Municipality', 34),
    (373, 'Dudhauli Municipality', 34),
    (374, 'Sunkoshi Rural Municipality', 34),
    (375, 'Hariharpurgadhi Rural Municipality', 34),
    (376, 'Tinpatan Rural Municipality', 34),
    (377, 'Marin Rural Municipality', 34),
    (378, 'Golanjor Rural Municipality', 34),
    (379, 'Phikkal Rural Municipality', 34),
    (380, 'Ghyanglekh Rural Municipality', 34),
    (381, 'Chautara Sangachowkgadi Municipality', 35),
    (382, 'Bahrabise Municipality', 35),
    (383, 'Melamchi Municipality', 35),
    (384, 'Balephi Rural Municipality', 35),
    (385, 'Sunkoshi Rural Municipality', 35),
    (386, 'Indrawati Rural Municipality', 35),
    (387, 'Jugal Rural Municipality', 35),
    (388, 'Panchpokhari Rural Municipality', 35),
    (389, 'Bhotekoshi Rural Municipality', 35),
    (390, 'Lisankhu Rural Municipality', 35),
    (391, 'Helambu Rural Municipality', 35),
    (392, 'Tripurasundari Rural Municipality', 35),
    (393, 'Baglung Municipality', 36),
    (394, 'Dhorpatan Municipality', 36),
    (395, 'Galkot Municipality', 36),
    (396, 'Jaimuni Municipality', 36),
    (397, 'Bareng Rural Municipality', 36),
    (398, 'Khathekhola Rural Municipality', 36),
    (399, 'Taman Khola Rural Municipality', 36),
    (400, 'Tara Khola Rural Municipality', 36),
    (401, 'Nishi Khola Rural Municipality', 36),
    (402, 'Badigad Rural Municipality', 36),
    (403, 'Gorkha Municipality', 37),
    (404, 'Palungtar Municipality', 37),
    (405, 'Sulikot Rural Municipality', 37),
    (406, 'Siranchowk Rural Municipality', 37),
    (407, 'Ajirkot Rural Municipality', 37),
    (408, 'Chumnubri Rural Municipality', 37),
    (409, 'Dharche Rural Municipality', 37),
    (410, 'Bhimsen Thapa Rural Municipality', 37),
    (411, 'Sahid Lakhan Rural Municipality', 37),
    (412, 'Aarughat Rural Municipality', 37),
    (413, 'Gandaki Rural Municipality', 37),
    (414, 'Pokhara Metropolitan City', 38),
    (415, 'Annapurna Rural Municipality', 38),
    (416, 'Machhapuchchhre Rural Municipality', 38),
    (417, 'Madi Rural Municipality', 38),
    (418, 'Rupa Rural Municipality', 38),
    (419, 'Besisahar Municipality', 39),
    (420, 'Madhya Nepal Municipality', 39),
    (421, 'Rainas Municipality', 39),
    (422, 'Sundarbazar Municipality', 39),
    (423, 'Dordi Rural Municipality', 39),
    (424, 'Dudhpokhari Rural Municipality', 39),
    (425, 'Kwhlosothar Rural Municipality', 39),
    (426, 'Marsyangdi Rural Municipality', 39),
    (427, 'Chame Rural Municipality', 40),
    (428, 'Nason Rural Municipality', 40),
    (429, 'NarpaBhumi Rural Municipality', 40),
    (430, 'Manang Ngisyang Rural Municipality', 40),
    (431, 'Gharpajhong Rural Municipality', 41),
    (432, 'Thasang Rural Municipality', 41),
    (433, 'Barhagaun Muktichhetra Rural Municipality', 41),
    (434, 'Lomanthang Rural Municipality', 41),
    (435, 'Lo-Ghekar Damodarkunda Rural Municipality', 41),
    (436, 'Beni Municipality', 42),
    (437, 'Annapurna Rural Municipality', 42),
    (438, 'Dhaulagiri Rural Municipality', 42),
    (439, 'Mangala Rural Municipality', 42),
    (440, 'Malika Rural Municipality', 42),
    (441, 'Raghuganga Rural Municipality', 42),
    (442, 'Kawasoti Municipality', 43),
    (443, 'Gaindakot Municipality', 43),
    (444, 'Devachuli Municipality', 43),
    (445, 'Madhya Bindu Municipality', 43),
    (446, 'Baudikali Rural Municipality', 43),
    (447, 'Bulingtar Rural Municipality', 43),
    (448, 'Binayi Tribeni Rural Municipality', 43),
    (449, 'Hupsekot Rural Municipality', 43),
    (450, 'Kushma Municipality', 44),
    (451, 'Phalewas Municipality', 44),
    (452, 'Jaljala Rural Municipality', 44),
    (453, 'Paiyun Rural Municipality', 44),
    (454, 'Mahashila Rural Municipality', 44),
    (455, 'Modi Rural Municipality', 44),
    (456, 'Bihadi Rural Municipality', 44),
    (457, 'Galyang Municipality', 45),
    (458, 'Chapakot Municipality', 45),
    (459, 'Putalibazar Municipality', 45),
    (460, 'Bheerkot Municipality', 45),
    (461, 'Waling Municipality', 45),
    (462, 'Arjun Chaupari Rural Municipality', 45),
    (463, 'Aandhikhola Rural Municipality', 45),
    (464, 'Kaligandaki Rural Municipality', 45),
    (465, 'Phedikhola Rural Municipality', 45),
    (466, 'Harinas Rural Municipality', 45),
    (467, 'Biruwa Rural Municipality', 45),
    (468, 'Bhanu Municipality', 46),
    (469, 'Bhimad Municipality', 46),
    (470, 'Byas Municipality', 46),
    (471, 'Suklagandaki Municipality', 46),
    (472, 'AnbuKhaireni Rural Municipality', 46),
    (473, 'Devghat Rural Municipality', 46),
    (474, 'Bandipur Rural Municipality', 46),
    (475, 'Rishing Rural Municipality', 46),
    (476, 'Ghiring Rural Municipality', 46),
    (477, 'Myagde Rural Municipality', 46),
    (478, 'Kapilvastu Municipality', 47),
    (479, 'Banganga Municipality', 47),
    (480, 'Buddhabhumi Municipality', 47),
    (481, 'Shivaraj Municipality', 47),
    (482, 'Krishnanagar Municipality', 47),
    (483, 'Maharajgunj Municipality', 47),
    (484, 'Mayadevi Rural Municipality', 47),
    (485, 'Yashodhara Rural Municipality', 47),
    (486, 'Suddhodan Rural Municipality', 47),
    (487, 'Bijaynagar Rural Municipality', 47),
    (488, 'Bardaghat Municipality', 48),
    (489, 'Ramgram Municipality', 48),
    (490, 'Sunwal Municipality', 48),
    (491, 'Susta Rural Municipality', 48),
    (492, 'Palhi Nandan Rural Municipality', 48),
    (493, 'Pratappur Rural Municipality', 48),
    (494, 'Sarawal Rural Municipality', 48),
    (495, 'Butwal Sub-Metropolitan City', 49),
    (496, 'Devdaha Municipality', 49),
    (497, 'Lumbini Sanskritik Municipality', 49),
    (498, 'Sainamaina Municipality', 49),
    (499, 'Siddharthanagar Municipality', 49),
    (500, 'Tilottama Municipality', 49),
    (501, 'Gaidahawa Rural Municipality', 49),
    (502, 'Kanchan Rural Municipality', 49),
    (503, 'Kotahimai Rural Municipality', 49),
    (504, 'Marchawari Rural Municipality', 49),
    (505, 'Mayadevi Rural Municipality', 49),
    (506, 'Omsatiya Rural Municipality', 49),
    (507, 'Rohini Rural Municipality', 49),
    (508, 'Sammarimai Rural Municipality', 49),
    (509, 'Siyari Rural Municipality', 49),
    (510, 'Suddodhan Rural Municipality', 49),
    (511, 'Sandhikharka Municipality', 50),
    (512, 'Sitganga Municipality', 50),
    (513, 'Bhumikasthan Municipality', 50),
    (514, 'Chhatradev Rural Municipality', 50),
    (515, 'Panini Rural Municipality', 50),
    (516, 'Malarani Rural Municipality', 50),
    (517, 'Resunga Municipality', 51),
    (518, 'Musikot Municipality', 51),
    (519, 'Rurukshetra Rural Municipality', 51),
    (520, 'Chhatrakot Rural Municipality', 51),
    (521, 'Gulmidarbar Rural Municipality', 51),
    (522, 'Chandrakot Rural Municipality', 51),
    (523, 'Satyawati Rural Municipality', 51),
    (524, 'Dhurkot Rural Municipality', 51),
    (525, 'Kaligandaki Rural Municipality', 51),
    (526, 'Isma Rural Municipality', 51),
    (527, 'Malika Rural Municipality', 51),
    (528, 'Madane Rural Municipality', 51),
    (529, 'Tansen Municipality', 52),
    (530, 'Rampur Municipality', 52),
    (531, 'Rainadevi Chhahara Rural Municipality', 52),
    (532, 'Ripdikot Rural Municipality', 52),
    (533, 'Bagnaskali Rural Municipality', 52),
    (534, 'Rambha Rural Municipality', 52),
    (535, 'Purbakhola Rural Municipality', 52),
    (536, 'Nisdi Rural Municipality', 52),
    (537, 'Mathagadhi Rural Municipality', 52),
    (538, 'Tinahu Rural Municipality', 52),
    (539, 'Ghorahi Sub-Metropolitan City', 53),
    (540, 'Tulsipur Sub-Metropolitan City', 53),
    (541, 'Lamahi Municipality', 53),
    (542, 'Gadhawa Rural Municipality', 53),
    (543, 'Rajpur Rural Municipality', 53),
    (544, 'Shantinagar Rural Municipality', 53),
    (545, 'Rapti Rural Municipality', 53),
    (546, 'Banglachuli Rural Municipality', 53),
    (547, 'Dangisharan Rural Municipality', 53),
    (548, 'Babai Rural Municipality', 53),
    (549, 'Sworgadwari Municipality', 54),
    (550, 'Pyuthan Municipality', 54),
    (551, 'Mandavi Rural Municipality', 54),
    (552, 'Sarumarani Rural Municipality', 54),
    (553, 'Ayirawati Rural Municipality', 54),
    (554, 'Mallarani Rural Municipality', 54),
    (555, 'Jhimruk Rural Municipality', 54),
    (556, 'Naubahini Rural Municipality', 54),
    (557, 'Gaumukhi Rural Municipality', 54),
    (558, 'Rolpa Municipality', 55),
    (559, 'Runtigadi Rural Municipality', 55),
    (560, 'Triveni Rural Municipality', 55),
    (561, 'Sunil Smiriti Rural Municipality', 55),
    (562, 'Lungri Rural Municipality', 55),
    (563, 'Sunchhahari Rural Municipality', 55),
    (564, 'Thawang Rural Municipality', 55),
    (565, 'Madi Rural Municipality', 55),
    (566, 'GangaDev Rural Municipality', 55),
    (567, 'Pariwartan Rural Municipality', 55),
    (568, 'Putha Uttarganga Rural Municipality', 56),
    (569, 'Bhume Rural Municipality', 56),
    (570, 'Sisne Rural Municipality', 56),
    (571, 'Nepalgunj Sub-Metropolitan City', 57),
    (572, 'Kohalpur Municipality', 57),
    (573, 'Rapti-Sonari Rural Municipality', 57),
    (574, 'Narainapur Rural Municipality', 57),
    (575, 'Duduwa Rural Municipality', 57),
    (576, 'Janaki Rural Municipality', 57),
    (577, 'Khajura Rural Municipality', 57),
    (578, 'Baijanath Rural Municipality', 57),
    (579, 'Gulariya Municipality', 58),
    (580, 'Rajapur Municipality', 58),
    (581, 'Madhuwan Municipality', 58),
    (582, 'Thakurbaba Municipality', 58),
    (583, 'Basgadhi Municipality', 58),
    (584, 'Barbardiya Municipality', 58),
    (585, 'Badhaiyatal Rural Municipality', 58),
    (586, 'Geruwa Rural Municipality', 58),
    (587, 'Aathabiskot Municipality', 59),
    (588, 'Musikot Municipality', 59),
    (589, 'Chaurjahari Municipality', 59),
    (590, 'SaniBheri Rural Municipality', 59),
    (591, 'Triveni Rural Municipality', 59),
    (592, 'Banphikot Rural Municipality', 59),
    (593, 'Kumakh Rural Municipality', 60),
    (594, 'Kalimati Rural Municipality', 60),
    (595, 'Chhatreshwari Rural Municipality', 60),
    (596, 'Darma Rural Municipality', 60),
    (597, 'Kapurkot Rural Municipality', 60),
    (598, 'Triveni Rural Municipality', 60),
    (599, 'Siddha Kumakh Rural Municipality', 60),
    (600, 'Bagchaur Municipality', 60),
    (601, 'Shaarda Municipality', 60),
    (602, 'Bangad Kupinde Municipality', 60),
    (603, 'Mudkechula Rural Municipality', 61),
    (604, 'Kaike Rural Municipality', 61),
    (605, 'She Phoksundo Rural Municipality', 61),
    (606, 'Jagadulla Rural Municipality', 61),
    (607, 'Dolpo Buddha Rural Municipality', 61),
    (608, 'Chharka Tongsong Rural Municipality', 61),
    (609, 'Thuli Bheri Municipality', 61),
    (610, 'Tripurasundari Municipality', 61),
    (611, 'Simkot Rural Municipality', 62),
    (612, 'Sarkegad Rural Municipality', 62),
    (613, 'Adanchuli Rural Municipality', 62),
    (614, 'Kharpunath Rural Municipality', 62),
    (615, 'Tanjakot Rural Municipality', 62),
    (616, 'Chankheli Rural Municipality', 62),
    (617, 'Namkha Rural Municipality', 62),
    (618, 'Tatopani Rural Municipality', 63),
    (619, 'Patarasi Rural Municipality', 63),
    (620, 'Tila Rural Municipality', 63),
    (621, 'Kanaka Sundari Rural Municipality', 63),
    (622, 'Sinja Rural Municipality', 63),
    (623, 'Hima Rural Municipality', 63),
    (624, 'Guthichaur Rural Municipality', 63),
    (625, 'Chandannath Municipality', 63),
    (626, 'Khandachakra Municipality', 64),
    (627, 'Raskot Municipality', 64),
    (628, 'Tilagufa Municipality', 64),
    (629, 'Narharinath Rural Municipality', 64),
    (630, 'Palata Rural Municipality', 64),
    (631, 'Shubha Kalika Rural Municipality', 64),
    (632, 'Sanni Triveni Rural Municipality', 64),
    (633, 'Pachaljharana Rural Municipality', 64),
    (634, 'Mahawai Rural Municipality', 64),
    (635, 'Khatyad Rural Municipality', 65),
    (636, 'Soru Rural Municipality', 65),
    (637, 'Mugum Karmarong Rural Municipality', 65),
    (638, 'Chhayanath Rara Municipality', 65),
    (639, 'Simta Rural Municipality', 66),
    (640, 'Barahatal Rural Municipality', 66),
    (641, 'Chaukune Rural Municipality', 66),
    (642, 'Chingad Rural Municipality', 66),
    (643, 'Gurbhakot Municipality', 66),
    (644, 'Birendranagar Municipality', 66),
    (645, 'Bheriganga Municipality', 66),
    (646, 'Panchapuri Municipality', 66),
    (647, 'Lekbeshi Municipality', 66),
    (648, 'Dullu Municipality', 67),
    (649, 'Gurans Rural Municipality', 67),
    (650, 'Bhairabi Rural Municipality', 67),
    (651, 'Naumule Rural Municipality', 67),
    (652, 'Mahabu Rural Municipality', 67),
    (653, 'Thantikandh Rural Municipality', 67),
    (654, 'Bhagawatimai Rural Municipality', 67),
    (655, 'Dungeshwar Rural Municipality', 67),
    (656, 'Aathabis Municipality', 67),
    (657, 'Narayan Municipality', 67),
    (658, 'Chamunda Bindrasaini Municipality', 67),
    (659, 'Chhedagad Municipality', 68),
    (660, 'Bheri Municipality', 68),
    (661, 'Nalgad Municipality', 68),
    (662, 'Junichande Rural Municipality', 68),
    (663, 'Kuse Rural Municipality', 68),
    (664, 'Barekot Rural Municipality', 68),
    (665, 'Shivalaya Rural Municipality', 68),
    (666, 'Mahakali Municipality', 69),
    (667, 'Shailyashikhar Municipality', 69),
    (668, 'Naugad Rural Municipality', 69),
    (669, 'Malikarjun Rural Municipality', 69),
    (670, 'Marma Rural Municipality', 69),
    (671, 'Lekam Rural Municipality', 69),
    (672, 'Duhun Rural Municipality', 69),
    (673, 'Vyans Rural Municipality', 69),
    (674, 'Apihimal Rural Municipality', 69),
    (675, 'Jayaprithvi Municipality', 70),
    (676, 'Bungal Municipality', 70),
    (677, 'Kedarsyu Rural Municipality', 70),
    (678, 'Thalara Rural Municipality', 70),
    (679, 'Bitthadchir Rural Municipality', 70),
    (680, 'Chhabis Pathibhera Rural Municipality', 70),
    (681, 'Khaptadchhanna Rural Municipality', 70),
    (682, 'Masta Rural Municipality', 70),
    (683, 'Durgathali Rural Municipality', 70),
    (684, 'Talkot Rural Municipality', 70),
    (685, 'Surma Rural Municipality', 70),
    (686, 'Saipal Rural Municipality', 70),
    (687, 'Badimalika Municipality', 71),
    (688, 'Triveni Municipality', 71),
    (689, 'Budhiganga Municipality', 71),
    (690, 'Budhinanda Municipality', 71),
    (691, 'Khaptad Chhededaha Rural Municipality', 71),
    (692, 'Swami Kartik Khapar Rural Municipality', 71),
    (693, 'Jagannath Rural Municipality', 71),
    (694, 'Himali Rural Municipality', 71),
    (695, 'Gaumul Rural Municipality', 71),
    (696, 'Dashrathchanda Municipality', 72),
    (697, 'Patan Municipality', 72),
    (698, 'Melauli Municipality', 72),
    (699, 'Purchaudi Municipality', 72),
    (700, 'Dogdakedar Rural Municipality', 72),
    (701, 'Dilashaini Rural Municipality', 72),
    (702, 'Sigas Rural Municipality', 72),
    (703, 'Pancheshwar Rural Municipality', 72),
    (704, 'Surnaya Rural Municipality', 72),
    (705, 'Shivanath Rural Municipality', 72),
    (706, 'Dipayal Silgadhi Municipality', 73),
    (707, 'Shikhar Municipality', 73),
    (708, 'Aadarsha Rural Municipality', 73),
    (709, 'Purbichauki Rural Municipality', 73),
    (710, 'K.I.Singh Rural Municipality', 73),
    (711, 'Jorayal Rural Municipality', 73),
    (712, 'Sayal Rural Municipality', 73),
    (713, 'Bogatan-Phudsil Rural Municipality', 73),
    (714, 'Badikedar Rural Municipality', 73),
    (715, 'Ramaroshan Rural Municipality', 74),
    (716, 'Chaurpati Rural Municipality', 74),
    (717, 'Turmakhand Rural Municipality', 74),
    (718, 'Mellekh Rural Municipality', 74),
    (719, 'Dhakari Rural Municipality', 74),
    (720, 'Bannigadi Jayagad Rural Municipality', 74),
    (721, 'Mangalsen Municipality', 74),
    (722, 'Kamalbazar Municipality', 74),
    (723, 'Sanfebagar Municipality', 74),
    (724, 'Panchadewal Binayak Municipality', 74),
    (725, 'Navadurga Rural Municipality', 75),
    (726, 'Aalitaal Rural Municipality', 75),
    (727, 'Ganyapadhura Rural Municipality', 75),
    (728, 'Bhageshwar Rural Municipality', 75),
    (729, 'Ajaymeru Rural Municipality', 75),
    (730, 'Amargadhi Municipality', 75),
    (731, 'Parshuram Municipality', 75),
    (732, 'Bhimdatta Municipality', 76),
    (733, 'Punarbas Municipality', 76),
    (734, 'Bedkot Municipality', 76),
    (735, 'Mahakali Municipality', 76),
    (736, 'Shuklaphanta Municipality', 76),
    (737, 'Belauri Municipality', 76),
    (738, 'Krishnapur Municipality', 76),
    (739, 'Laljhadi Rural Municipality', 76),
    (740, 'Beldandi Rural Municipality', 76),
    (741, 'Janaki Rural Municipality', 77),
    (742, 'Kailari Rural Municipality', 77),
    (743, 'Joshipur Rural Municipality', 77),
    (744, 'Bardagoriya Rural Municipality', 77),
    (745, 'Mohanyal Rural Municipality', 77),
    (746, 'Chure Rural Municipality', 77),
    (747, 'Tikapur Municipality', 77),
    (748, 'Ghodaghodi Municipality', 77),
    (749, 'Lamkichuha Municipality', 77),
    (750, 'Bhajni Municipality', 77),
    (751, 'Godawari Municipality', 77),
    (752, 'Gauriganga Municipality', 77),
    (753, 'Dhangadhi Sub-Metropolitan City', 77)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- 3. kyc: Nepal-specialized KYC (Know Your Customer) record.
--    Distinct from the "users" table (login/staff accounts) - this
--    table holds the customer/applicant data being verified.
--
--    Permanent and temporary address each carry their own three
--    location columns (province / district / municipality) plus a
--    ward number.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kyc (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    full_name                   VARCHAR(200) NOT NULL,
    gender                      VARCHAR(10) NOT NULL CHECK (gender IN ('Male', 'Female', 'Other')),
    dob_bs                      VARCHAR(10),
    dob_ad                      DATE NOT NULL,

    citizenship_number          VARCHAR(50) NOT NULL UNIQUE,
    citizenship_issued_district VARCHAR(100),
    citizenship_issued_date     DATE,

    phone_number                VARCHAR(20) NOT NULL,
    email                       VARCHAR(255),

    -- Permanent address (required)
    permanent_province_id       INTEGER NOT NULL REFERENCES provinces(id),
    permanent_district_id       INTEGER NOT NULL REFERENCES districts(id),
    permanent_municipality_id   INTEGER NOT NULL REFERENCES municipalities(id),
    permanent_ward_no           SMALLINT NOT NULL,

    -- Temporary address (optional)
    temporary_province_id       INTEGER REFERENCES provinces(id),
    temporary_district_id       INTEGER REFERENCES districts(id),
    temporary_municipality_id   INTEGER REFERENCES municipalities(id),
    temporary_ward_no           SMALLINT,

    father_name                 VARCHAR(200),
    mother_name                 VARCHAR(200),
    grandfather_name            VARCHAR(200),
    occupation                  VARCHAR(100),
    pan_number                  VARCHAR(20),

    created_by                  VARCHAR(255),
    created_date                TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_updated_by             VARCHAR(255),
    last_updated_date           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_kyc_permanent_municipality_id ON kyc (permanent_municipality_id);
CREATE INDEX IF NOT EXISTS idx_kyc_temporary_municipality_id ON kyc (temporary_municipality_id);
